// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.1.0-1-g1f618f69-wicked-fork

package bestsellers

import (
	"time"
)

type Bestseller struct {
	ID          int32      `json:"id"`
	Name        string     `json:"name"`
	Firstbstime *time.Time `json:"firstbstime"`
}
