// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.1.0-1-g1f618f69-wicked-fork

package vitems

import (
	"github.com/stumble/dcache"
	"github.com/stumble/wpgx"
)

// BeforeDump allows you to edit result before dump.
type BeforeDump func(m *VItem)

func New(db wpgx.WGConn, cache *dcache.DCache) *Queries {
	return &Queries{db: db, cache: cache}
}

type Queries struct {
	db    wpgx.WGConn
	cache *dcache.DCache
}

func (q *Queries) WithTx(tx *wpgx.WTx) *Queries {
	return &Queries{
		db:    tx,
		cache: q.cache,
	}
}

func (q *Queries) WithCache(cache *dcache.DCache) *Queries {
	return &Queries{
		db:    q.db,
		cache: cache,
	}
}

var Schema = `
CREATE MATERIALIZED VIEW IF NOT EXISTS v_items AS
  SELECT
    items.ID,
    items.Name,
    items.Description,
    items.Category,
    items.Price,
    items.Thumbnail,
    items.QRCode,
    items.Metadata,
    items.CreatedAt,
    items.UpdatedAt,
    sum(orders.Price) AS totalVolume,
    sum(
      CASE WHEN (orders.CreatedAt > now() - interval '30 day') THEN orders.Price ELSE 0 END
    ) AS last30dVolume,
    max(listings.Price)::bigint AS floorPrice
  FROM
    items
    LEFT JOIN Orders ON items.ID = orders.ItemID
    LEFT JOIN Listings ON items.ID = listings.ItemID
  GROUP BY
      items.ID;

CREATE UNIQUE INDEX v_items_id_unique_idx
  ON v_items (ID);

CREATE UNIQUE INDEX v_items_floor_price_idx
  ON v_items (floorPrice);

CREATE UNIQUE INDEX v_items_total_volume_idx
  ON v_items (totalVolume);

CREATE UNIQUE INDEX v_items_total_last_30d_volume_idx
  ON v_items (last30dVolume);
`
