// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.1.0-1-g1f618f69-wicked-fork

package items

import (
	"github.com/stumble/dcache"
	"github.com/stumble/wpgx"
)

// BeforeDump allows you to edit result before dump.
type BeforeDump func(m *Item)

func New(db wpgx.WGConn, cache *dcache.DCache) *Queries {
	return &Queries{db: db, cache: cache}
}

type Queries struct {
	db    wpgx.WGConn
	cache *dcache.DCache
}

func (q *Queries) WithTx(tx *wpgx.WTx) *Queries {
	return &Queries{
		db:    tx,
		cache: q.cache,
	}
}

func (q *Queries) WithCache(cache *dcache.DCache) *Queries {
	return &Queries{
		db:    q.db,
		cache: cache,
	}
}

var Schema = `
CREATE TYPE ItemCategory AS ENUM (
    'ALCOHOL ',
    'DRUG',
    'DRINK',
    'FRUIT',
    'VEGETABLE'
);

CREATE TABLE IF NOT EXISTS Items (
   ID           BIGSERIAL GENERATED ALWAYS AS IDENTITY,
   Name         VARCHAR(255)        NOT NULL,
   Description  VARCHAR(255)        NOT NULL,
   Category     ItemCategory        NOT NULL,
   Price        DECIMAL(10,2)       NOT NULL,
   Thumbnail    TEXT                NOT NULL,
   QRCode       CHAR(1024),
   Metadata     JSON,
   CreatedAt    TIMESTAMP           NOT NULL DEFAULT NOW(),
   UpdatedAt    TIMESTAMP           NOT NULL DEFAULT NOW(),
   PRIMARY KEY(ID)
) PARTITION BY RANGE (ID);

CREATE TABLE IF NOT EXISTS items_id_le_1000
PARTITION OF Items FOR VALUES
FROM (0) TO (1000);

-- local index on (Name)
CREATE INDEX IF NOT EXISTS items_id_le_1000_name_idx
ON items_id_le_1000 (Name);

-- global index on created_at
CREATE INDEX IF NOT EXISTS items_created_at_idx
    ON Items (CreatedAt);
`
