// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.1.0-1-g1f618f69-wicked-fork

package orders

import (
	"github.com/stumble/dcache"
	"github.com/stumble/wpgx"
)

// BeforeDump allows you to edit result before dump.
type BeforeDump func(m *Order)

func New(db wpgx.WGConn, cache *dcache.DCache) *Queries {
	return &Queries{db: db, cache: cache}
}

type Queries struct {
	db    wpgx.WGConn
	cache *dcache.DCache
}

func (q *Queries) WithTx(tx *wpgx.WTx) *Queries {
	return &Queries{
		db:    tx,
		cache: q.cache,
	}
}

func (q *Queries) WithCache(cache *dcache.DCache) *Queries {
	return &Queries{
		db:    q.db,
		cache: cache,
	}
}

var Schema = `
CREATE TABLE IF NOT EXISTS Orders (
   ID        INT GENERATED ALWAYS AS IDENTITY,
   UserID    INT references Users(ID) NOT NULL,
   ItemID    INT references Items(ID) NOT NULL,
   Price     BIGINT NOT NULL,
   CreatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
   IsDeleted BOOLEAN NOT NULL,
   PRIMARY KEY(ID)
);

CREATE INDEX orders_item_id_idx ON orders (ItemID);
`
